### ISSUE TITLE
"can't deliver to" 

### ISSUE THREAD

**Issue by 89gsc** [sscholl/screeps#2]
--> creeps[10].run
[11:22:56]    --> Creep.run
[11:22:56]      --> Creep.taskDeliver
[11:22:56]        --> Creep.taskDeliver
[11:22:56]          ERROR: [E18N39] [FhsnFJ] can't deliver to yxPHLf: -8
[11:22:56]        <-- Creep.taskDeliver [0.35] 
[11:22:56]      <-- Creep.taskDeliver [0.40] 
[11:22:56]    <-- Creep.run [0.43] 
[11:22:56]  <-- creeps[10].run [3.52] 

I get this a hell of a lot:

2 screeps always end up here throwing that error, one is a builder type screep with full energy preventing the transfer:

http://prntscr.com/bx7fgt

I am not sure if this is because the room is still under protection? 

Anyway yeah seems to be every tick that throws up, I can suicide both creeps but 2 new ones will end up having the same issue.

**Comment by 89gsc** [comment]
When I delete the builder of the 2 the other creep will go away and start doing other stuff, it hasn't come back yet so could be a one off, but it happened all last night.

**Comment by sscholl** [comment]
There is a problem with a task combination . The builder tries to build, but i does not find the construction and the carrier tries to transfer the energy, but the builder is full. 
See http://support.screeps.com/hc/en-us/articles/203013212-Creep#transfer

**Comment by 89gsc** [comment]
Got you thanks for clearing that up its only an occasional issue it seems most of the time it wont happen.
